# serverless.yml

service: client-server

provider:
    name: aws
    runtime: nodejs6.10
    stage: dev
    region: eu-west-2

plugins:
    - serverless-finch

custom:
    client:
        bucketName: unique-bucket-client
        distributionFolder: build
        indexDocument: index.html
        errorDocument: index.html
