#!/bin/bash


rm -rf ../static/react_app
mkdir ../static/react_app
find build -type f -maxdepth 1 -exec mv {} ../static/react_app \;
find build/static/js -type f -maxdepth 1 -exec mv {} ../static/js \;
find build/static/css -type f -maxdepth 1 -exec mv {} ../static/css \;
rm -rf build