language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - export FLASK_ENV=production
# command to run tests
script:
  - python app.py
