export const dummyExcelData = {
    "headers": ["Title", "First Name", "Last Name", " Email", "Employment Type", "Employment Type Looking for", "Job Types", "Gender", "linkedln", "Current Salary", "Desired Salary", "Company", "Contract Rate", "Education", "Degree", "Employer (Company)", "Mobile", "Job Title 1", "Keyword", "Skills", "Start1. MM-DD-YYYY", "End1. MM-DD-YYYY", "Zip code"],
    "data": [{
        "Title": "Mr",
        "First Name": "MehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdi",
        "Last Name": "Este",
        " Email": "m.este@thesearchbase.com",
        "Employment Type": "FULL-TIME",
        "Employment Type Looking for": "PERMANENT",
        "Job Types": "PERMANENT",
        "Gender": "MALE",
        "linkedln": "https://www.linkedin.com/in/mehdi-este-142460107/",
        "Current Salary": 100000,
        "Desired Salary": 250000,
        "Company": "entrepreneurship, sales, engineering",
        "Contract Rate": 0,
        "Education": "Degree",
        "Degree": "University",
        "Employer (Company)": "TheSearchBase",
        "Mobile": 7777777777,
        "Job Title 1": "CEO & Director",
        "Keyword": "sales director, well connected",
        "Skills": "Python, React, Flask",
        "Start1. MM-DD-YYYY": "2026-09-23T21:00:00.000Z",
        "End1. MM-DD-YYYY": "2019-03-02T21:00:00.000Z",
        "Zip code": "W1 3AE"
    }, {
        "Title": "Mrs",
        "First Name": "Alexa",
        "Last Name": "Amazon",
        " Email": "amazon@amazon.co.uk",
        "Employment Type": "FULL-TIME",
        "Employment Type Looking for": "CONTRACT",
        "Job Types": "CONTRACT",
        "Gender": "FEMALE",
        "Current Salary": 350,
        "Desired Salary": 500,
        "Company": "customer service, sales",
        "Contract Interval(Days until end so 60 is like 2 month contract)": 60,
        "Contract Rate": 500,
        "Education": "Masters",
        "Degree": "University",
        "Employer (Company)": "Amazon",
        "Mobile": 34583945,
        "Job Title 1": "Sales Assistant",
        "Keyword": "sales support, sales adminstrator",
        "Skills": "MySQL",
        "Start1. MM-DD-YYYY": "Just Looking",
        "End1. MM-DD-YYYY": "2019-03-03T21:00:00.000Z",
        "Zip code": "W4 6YT"
    }, {
        "Title": "Mr",
        "First Name": "Evgeniy",
        "Last Name": "Tonchev",
        " Email": "tonchev@thesearchbase.com",
        "Employment Type": "PART-TIME",
        "Employment Type Looking for": "PERMANENT",
        "Job Types": "PERMANENT",
        "Gender": "MALE",
        "linkedln": "https://www.linkedin.com/in/mehdi-este-142460107/",
        "Current Salary": 100000,
        "Desired Salary": 150000,
        "Company": "Technology, Engineering",
        "Contract Rate": 0,
        "Education": "Degree",
        "Degree": "GCSE",
        "Employer (Company)": "TheSearchBase",
        "Mobile": 456000,
        "Job Title 1": "CTO & Director",
        "Keyword": "cto, head of engineering",
        "Skills": "Python, MySQL, Linux",
        "Start1. MM-DD-YYYY": "2026-09-22T21:00:00.000Z",
        "End1. MM-DD-YYYY": "2019-03-04T21:00:00.000Z",
        "Zip code": "S5 6ND"
    }, {
        "Title": "Mr",
        "First Name": "Mehdi",
        "Last Name": "Este",
        " Email": "m.este@thesearchbase.com",
        "Employment Type": "PART-TIME",
        "Employment Type Looking for": "PERMANENT",
        "Job Types": "CONTRACT",
        "Gender": "MALE",
        "Current Salary": 400000,
        "Desired Salary": 50000,
        "Company": "entrepreneurship, sales, engineering",
        "Contract Interval(Days until end so 60 is like 2 month contract)": 120,
        "Contract Rate": 250,
        "Education": "PhD",
        "Degree": "A-Levels",
        "Employer (Company)": "Google",
        "Mobile": 6546456456,
        "Job Title 1": "Software Enginner",
        "Keyword": ".net developer, machine learning",
        "Skills": "python, C#, java",
        "Start1. MM-DD-YYYY": "Just Looking",
        "End1. MM-DD-YYYY": "2019-03-05T21:00:00.000Z",
        "Zip code": "W1 3AE"
    }, {
        "Title": "Mrs",
        "First Name": "Alexa",
        "Last Name": "Amazon",
        " Email": "amazon@amazon.co.uk",
        "Employment Type": "FULL-TIME",
        "Employment Type Looking for": "PERMANENT",
        "Job Types": "CONTRACT",
        "Gender": "FEMALE",
        "Current Salary": 200,
        "Desired Salary": 40000,
        "Company": "customer service, sales",
        "Contract Interval(Days until end so 60 is like 2 month contract)": 90,
        "Contract Rate": 150,
        "Education": "Degree",
        "Degree": "University",
        "Employer (Company)": "Amazon",
        "Mobile": 456456456,
        "Job Title 1": "Sales Director",
        "Keyword": "sales strategy, sales qualification, sales leads",
        "Skills": "Salesforce CRM, list of contacts",
        "Start1. MM-DD-YYYY": "Just Looking",
        "End1. MM-DD-YYYY": "2019-03-06T21:00:00.000Z",
        "Zip code": "W4 6YT"
    }, {
        "Title": "Mr",
        "First Name": "Evgeniy",
        "Last Name": "Tonchev",
        " Email": "tonchev@thesearchbase.com",
        "Employment Type": "FULL-TIME",
        "Employment Type Looking for": "CONTRACT",
        "Job Types": "CONTRACT",
        "Gender": "MALE",
        "Current Salary": 300000,
        "Desired Salary": 450,
        "Company": "Technology, Engineering",
        "Contract Interval(Days until end so 60 is like 2 month contract)": 30,
        "Contract Rate": 100,
        "Education": "Masters",
        "Degree": "University",
        "Employer (Company)": "TheSearchBase",
        "Mobile": 45645645645,
        "Job Title 1": "Server Side Developer",
        "Keyword": "React developer, python developer",
        "Skills": "Python, React, Redux, Saga",
        "Start1. MM-DD-YYYY": "2021-10-30T21:00:00.000Z",
        "End1. MM-DD-YYYY": "2019-03-07T21:00:00.000Z",
        "Zip code": "S5 6ND"
    }]
};
