export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const DEMO_REQUEST = 'DEMO_REQUEST';
export const DEMO_SUCCESS = 'DEMO_SUCCESS';
export const DEMO_FAILURE = 'DEMO_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const NEW_RESET_PASSWORD_REQUEST = 'NEW_RESET_PASSWORD_REQUEST';
export const NEW_RESET_PASSWORD_SUCCESS = 'NEW_RESET_PASSWORD_SUCCESS';
export const NEW_RESET_PASSWORD_FAILURE = 'NEW_RESET_PASSWORD_FAILURE';


export const LOGOUT = 'LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';


export const VERIFY_ACCOUNT_REQUEST = 'VERIFY_ACCOUNT_REQUEST';
export const VERIFY_ACCOUNT_SUCCESS = 'VERIFY_ACCOUNT_SUCCESS';
export const VERIFY_ACCOUNT_FAILURE = 'VERIFY_ACCOUNT_FAILURE';


export const FETCH_OPTIONS_REQUEST = 'FETCH_OPTIONS_REQUEST';
export const FETCH_OPTIONS_SUCCESS = 'FETCH_OPTIONS_SUCCESS';
export const FETCH_OPTIONS_FAILURE = 'FETCH_OPTIONS_FAILURE';


// Assistant
export const FETCH_ASSISTANTS_REQUEST = 'FETCH_ASSISTANTS_REQUEST';
export const FETCH_ASSISTANTS_SUCCESS = 'FETCH_ASSISTANTS_SUCCESS';
export const FETCH_ASSISTANTS_FAILURE = 'FETCH_ASSISTANTS_FAILURE';

export const FETCH_ASSISTANT_REQUEST = 'FETCH_ASSISTANT_REQUEST';
export const FETCH_ASSISTANT_SUCCESS = 'FETCH_ASSISTANT_SUCCESS';
export const FETCH_ASSISTANT_FAILURE = 'FETCH_ASSISTANT_FAILURE';

export const CHANGE_ASSISTANT_STATUS_REQUEST = 'CHANGE_ASSISTANT_STATUS_REQUEST';
export const CHANGE_ASSISTANT_STATUS_SUCCESS = 'CHANGE_ASSISTANT_STATUS_SUCCESS';
export const CHANGE_ASSISTANT_STATUS_FAILURE = 'CHANGE_ASSISTANT_STATUS_FAILURE';

export const ADD_ASSISTANT_REQUEST = 'ADD_ASSISTANTS_REQUEST';
export const ADD_ASSISTANT_SUCCESS = 'ADD_ASSISTANT_SUCCESS';
export const ADD_ASSISTANT_FAILURE = 'ADD_ASSISTANT_FAILURE';

export const UPDATE_ASSISTANT_REQUEST = 'UPDATE_ASSISTANT_REQUEST';
export const UPDATE_ASSISTANT_SUCCESS = 'UPDATE_ASSISTANT_SUCCESS';
export const UPDATE_ASSISTANT_FAILURE = 'UPDATE_ASSISTANT_FAILURE';

export const UPDATE_ASSISTANT_CONFIGS_REQUEST = 'UPDATE_ASSISTANT_CONFIGS_REQUEST';
export const UPDATE_ASSISTANT_CONFIGS_SUCCESS = 'UPDATE_ASSISTANT_CONFIGS_SUCCESS';
export const UPDATE_ASSISTANT_CONFIGS_FAILURE = 'UPDATE_ASSISTANT_CONFIGS_FAILURE';

export const DELETE_ASSISTANT_REQUEST = 'DELETE_ASSISTANT_REQUEST';
export const DELETE_ASSISTANT_SUCCESS = 'DELETE_ASSISTANT_SUCCESS';
export const DELETE_ASSISTANT_FAILURE = 'DELETE_ASSISTANT_FAILURE';

// Assistant Custom Logo
export const UPLOAD_ASSISTANT_LOGO_REQUEST = 'UPLOAD_ASSISTANT_LOGO_REQUEST';
export const UPLOAD_ASSISTANT_LOGO_SUCCESS = 'UPLOAD_ASSISTANT_LOGO_SUCCESS';
export const UPLOAD_ASSISTANT_LOGO_FAILURE = 'UPLOAD_ASSISTANT_LOGO_FAILURE';

export const DELETE_ASSISTANT_LOGO_REQUEST = 'DELETE_ASSISTANT_LOGO_REQUEST';
export const DELETE_ASSISTANT_LOGO_SUCCESS = 'DELETE_ASSISTANT_LOGO_SUCCESS';
export const DELETE_ASSISTANT_LOGO_FAILURE = 'DELETE_ASSISTANT_LOGO_FAILURE';

// Update Flow (Script)
export const UPDATE_FLOW_REQUEST = 'UPDATE_FLOW_REQUEST';
export const UPDATE_FLOW_SUCCESS = 'UPDATE_FLOW_SUCCESS';
export const UPDATE_FLOW_FAILURE = 'UPDATE_FLOW_FAILURE';

// CRM Connection
export const CONNECT_ASSISTANT_TO_CRM_REQUEST = 'CONNECT_ASSISTANT_TO_CRM_REQUEST';
export const CONNECT_ASSISTANT_TO_CRM_SUCCESS = 'CONNECT_ASSISTANT_TO_CRM_SUCCESS';
export const CONNECT_ASSISTANT_TO_CRM_FAILURE = 'CONNECT_ASSISTANT_TO_CRM_FAILURE';

export const DISCONNECT_ASSISTANT_FROM_CRM_REQUEST = 'DISCONNECT_ASSISTANT_FROM_CRM_REQUEST';
export const DISCONNECT_ASSISTANT_FROM_CRM_SUCCESS = 'DISCONNECT_ASSISTANT_FROM_CRM_SUCCESS';
export const DISCONNECT_ASSISTANT_FROM_CRM_FAILURE = 'DISCONNECT_ASSISTANT_FROM_CRM_FAILURE';

// Calendar Connection
export const CONNECT_ASSISTANT_TO_CALENDAR_REQUEST = 'CONNECT_ASSISTANT_TO_CALENDAR_REQUEST';
export const CONNECT_ASSISTANT_TO_CALENDAR_SUCCESS = 'CONNECT_ASSISTANT_TO_CALENDAR_SUCCESS';
export const CONNECT_ASSISTANT_TO_CALENDAR_FAILURE = 'CONNECT_ASSISTANT_TO_CALENDAR_FAILURE';

export const DISCONNECT_ASSISTANT_FROM_CALENDAR_REQUEST = 'DISCONNECT_ASSISTANT_FROM_CALENDAR_REQUEST';
export const DISCONNECT_ASSISTANT_FROM_CALENDAR_SUCCESS = 'DISCONNECT_ASSISTANT_FROM_CALENDAR_SUCCESS';
export const DISCONNECT_ASSISTANT_FROM_CALENDAR_FAILURE = 'DISCONNECT_ASSISTANT_FROM_CALENDAR_FAILURE';

// Messenger Connection
export const CONNECT_ASSISTANT_TO_MESSENGER_REQUEST = 'CONNECT_ASSISTANT_TO_MESSENGER_REQUEST';
export const CONNECT_ASSISTANT_TO_MESSENGER_SUCCESS = 'CONNECT_ASSISTANT_TO_MESSENGER_SUCCESS';
export const CONNECT_ASSISTANT_TO_MESSENGER_FAILURE = 'CONNECT_ASSISTANT_TO_MESSENGER_FAILURE';

export const DISCONNECT_ASSISTANT_FROM_MESSENGER_REQUEST = 'DISCONNECT_ASSISTANT_FROM_MESSENGER_REQUEST';
export const DISCONNECT_ASSISTANT_FROM_MESSENGER_SUCCESS = 'DISCONNECT_ASSISTANT_FROM_MESSENGER_SUCCESS';
export const DISCONNECT_ASSISTANT_FROM_MESSENGER_FAILURE = 'DISCONNECT_ASSISTANT_FROM_MESSENGER_FAILURE';

// Auto Pilot Connection
export const CONNECT_ASSISTANT_TO_AUTO_PILOT_REQUEST = 'CONNECT_ASSISTANT_TO_AUTO_PILOT_REQUEST';
export const CONNECT_ASSISTANT_TO_AUTO_PILOT_SUCCESS = 'CONNECT_ASSISTANT_TO_AUTO_PILOT_SUCCESS';
export const CONNECT_ASSISTANT_TO_AUTO_PILOT_FAILURE = 'CONNECT_ASSISTANT_TO_AUTO_PILOT_FAILURE';

export const DISCONNECT_ASSISTANT_FROM_AUTO_PILOT_REQUEST = 'DISCONNECT_ASSISTANT_FROM_AUTO_PILOT_REQUEST';
export const DISCONNECT_ASSISTANT_FROM_AUTO_PILOT_SUCCESS = 'DISCONNECT_ASSISTANT_FROM_AUTO_PILOT_SUCCESS';
export const DISCONNECT_ASSISTANT_FROM_AUTO_PILOT_FAILURE = 'DISCONNECT_ASSISTANT_FROM_AUTO_PILOT_FAILURE';


// Account
export const GET_ACCOUNT_REQUEST = 'GET_ACCOUNT_REQUEST';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const GET_ACCOUNT_FAILURE = 'GET_ACCOUNT_FAILURE';

export const SAVE_PROFILE_DETAILS_REQUEST = 'SAVE_PROFILE_DETAILS_REQUEST';
export const SAVE_PROFILE_DETAILS_SUCCESS = 'SAVE_PROFILE_DETAILS_SUCCESS';
export const SAVE_PROFILE_DETAILS_FAILURE = 'SAVE_PROFILE_DETAILS_FAILURE';

export const SAVE_COMPANY_DETAILS_REQUEST = 'SAVE_COMPANY_DETAILS_REQUEST';
export const SAVE_COMPANY_DETAILS_SUCCESS = 'SAVE_COMPANY_DETAILS_SUCCESS';
export const SAVE_COMPANY_DETAILS_FAILURE = 'SAVE_COMPANY_DETAILS_FAILURE';

export const CHANGE_PASS_REQUEST = 'CHANGE_PASS_REQUEST';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CHANGE_PASS_FAILURE = 'CHANGE_PASS_FAILURE';

// Company Custom Logo
export const UPLOAD_LOGO_REQUEST = 'UPLOAD_LOGO_REQUEST';
export const UPLOAD_LOGO_SUCCESS = 'UPLOAD_LOGO_SUCCESS';
export const UPLOAD_LOGO_FAILURE = 'UPLOAD_LOGO_FAILURE';

export const DELETE_LOGO_REQUEST = 'DELETE_LOGO_REQUEST';
export const DELETE_LOGO_SUCCESS = 'DELETE_LOGO_SUCCESS';
export const DELETE_LOGO_FAILURE = 'DELETE_LOGO_FAILURE';


// Conversations
export const FETCH_CONVERSATIONS_REQUEST = 'FETCH_CONVERSATIONS_REQUEST';
export const FETCH_CONVERSATIONS_SUCCESS = 'FETCH_CONVERSATIONS_SUCCESS';
export const FETCH_CONVERSATIONS_FAILURE = 'FETCH_CONVERSATIONS_FAILURE';

export const DELETE_CONVERSATIONS_REQUEST = 'DELETE_CONVERSATIONS_REQUEST';
export const DELETE_CONVERSATIONS_SUCCESS = 'DELETE_CONVERSATIONS_SUCCESS';
export const DELETE_CONVERSATIONS_FAILURE = 'DELETE_CONVERSATIONS_FAILURE';

export const CLEAR_ALL_CONVERSATIONS_REQUEST = 'CLEAR_ALL_CONVERSATIONS_REQUEST';
export const CLEAR_ALL_CONVERSATIONS_SUCCESS = 'CLEAR_ALL_CONVERSATIONS_SUCCESS';
export const CLEAR_ALL_CONVERSATIONS_FAILURE = 'CLEAR_ALL_CONVERSATIONS_FAILURE';

export const UPDATE_CONVERSATION_STATUS_REQUEST = 'UPDATE_CONVERSATION_STATUS_REQUEST';
export const UPDATE_CONVERSATION_STATUS_SUCCESS = 'UPDATE_CONVERSATION_STATUS_SUCCESS';
export const UPDATE_CONVERSATION_STATUS_FAILURE = 'UPDATE_CONVERSATION_STATUS_FAILURE';


export const GET_DATABASES_LIST_REQUEST = 'GET_DATABASES_LIST_REQUEST';
export const GET_DATABASES_LIST_SUCCESS = 'GET_DATABASES_LIST_SUCCESS';
export const GET_DATABASES_LIST_FAILURE = 'GET_DATABASES_LIST_FAILURE';

export const UPLOAD_DATABASE_REQUEST = 'UPLOAD_DATABASE_REQUEST';
export const UPLOAD_DATABASE_SUCCESS = 'UPLOAD_DATABASE_SUCCESS';
export const UPLOAD_DATABASE_FAILURE = 'UPLOAD_DATABASE_FAILURE';

export const FETCH_DATABASE_REQUEST = 'FETCH_DATABASE_REQUEST';
export const FETCH_DATABASE_SUCCESS = 'FETCH_DATABASE_SUCCESS';
export const FETCH_DATABASE_FAILURE = 'FETCH_DATABASE_FAILURE';
export const RESET_DATABASE = 'RESET_DATABASE';

export const UPDATE_DATABASE_REQUEST = 'UPDATE_DATABASE_REQUEST';
export const UPDATE_DATABASE_SUCCESS = 'UPDATE_DATABASE_SUCCESS';
export const UPDATE_DATABASE_FAILURE = 'UPDATE_DATABASE_FAILURE';

export const DELETE_DATABASE_REQUEST = 'DELETE_DATABASE_REQUEST';
export const DELETE_DATABASE_SUCCESS = 'DELETE_DATABASE_SUCCESS';
export const DELETE_DATABASE_FAILURE = 'DELETE_DATABASE_FAILURE';

// Users Management
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';


// Marketplace
// This is to be used from marketplace.item to initilize the page
export const PING_MARKETPLACE_REQUEST = 'PING_MARKETPLACE_REQUEST';
export const PING_MARKETPLACE_SUCCESS = 'PING_MARKETPLACE_SUCCESS';
export const PING_MARKETPLACE_FAILURE = 'PING_MARKETPLACE_FAILURE';

// This is to be used from assistant
export const FETCH_MARKETPLACE_REQUEST = 'FETCH_MARKETPLACE_REQUEST';
export const FETCH_MARKETPLACE_SUCCESS = 'FETCH_MARKETPLACE_SUCCESS';
export const FETCH_MARKETPLACE_FAILURE = 'FETCH_MARKETPLACE_FAILURE';

// This is to be used from marketplace.item to connect
export const CONNECT_MARKETPLACE_REQUEST = 'CONNECT_MARKETPLACE_REQUEST';
export const CONNECT_MARKETPLACE_SUCCESS = 'CONNECT_MARKETPLACE_SUCCESS';
export const CONNECT_MARKETPLACE_FAILURE = 'CONNECT_MARKETPLACE_FAILURE';

// This is to be used from marketplace.item to disconnect
export const DISCONNECT_MARKETPLACE_REQUEST = 'DISCONNECT_MARKETPLACE_REQUEST';
export const DISCONNECT_MARKETPLACE_SUCCESS = 'DISCONNECT_MARKETPLACE_SUCCESS';
export const DISCONNECT_MARKETPLACE_FAILURE = 'DISCONNECT_MARKETPLACE_FAILURE';


// CRM EXPORT RECRUITER VALUE REPORT
export const EXPORT_RECRUITER_VALUE_REPORT_REQUEST = 'EXPORT_RECRUITER_VALUE_REPORT_REQUEST';
export const EXPORT_RECRUITER_VALUE_REPORT_SUCCESS = 'EXPORT_RECRUITER_VALUE_REPORT_SUCCESS';
export const EXPORT_RECRUITER_VALUE_REPORT_FAILURE = 'EXPORT_RECRUITER_VALUE_REPORT_FAILURE';


// Analytics
export const FETCH_ANALYTICS_REQUEST = 'FETCH_ANALYTICS_REQUEST';
export const FETCH_ANALYTICS_SUCCESS = 'FETCH_ANALYTICS_SUCCESS';
export const FETCH_ANALYTICS_FAILURE = 'FETCH_ANALYTICS_FAILURE';


// AutoPilot
export const FETCH_AUTOPILOTS_REQUEST = 'FETCH_AUTOPILOTS_REQUEST';
export const FETCH_AUTOPILOTS_SUCCESS = 'FETCH_AUTOPILOTS_SUCCESS';
export const FETCH_AUTOPILOTS_FAILURE = 'FETCH_AUTOPILOTS_FAILURE';

export const FETCH_AUTOPILOT_REQUEST = 'FETCH_AUTOPILOT_REQUEST';
export const FETCH_AUTOPILOT_SUCCESS = 'FETCH_AUTOPILOT_SUCCESS';
export const FETCH_AUTOPILOT_FAILURE = 'FETCH_AUTOPILOT_FAILURE';

export const ADD_AUTOPILOT_REQUEST = 'ADD_AUTOPILOT_REQUEST';
export const ADD_AUTOPILOT_SUCCESS = 'ADD_AUTOPILOT_SUCCESS';
export const ADD_AUTOPILOT_FAILURE = 'ADD_AUTOPILOT_FAILURE';

export const UPDATE_AUTOPILOT_REQUEST = 'UPDATE_AUTOPILOT_REQUEST';
export const UPDATE_AUTOPILOT_SUCCESS = 'UPDATE_AUTOPILOT_SUCCESS';
export const UPDATE_AUTOPILOT_FAILURE = 'UPDATE_AUTOPILOT_FAILURE';

export const UPDATE_AUTOPILOT_CONFIGS_REQUEST = 'UPDATE_AUTOPILOT_CONFIGS_REQUEST';
export const UPDATE_AUTOPILOT_CONFIGS_SUCCESS = 'UPDATE_AUTOPILOT_CONFIGS_SUCCESS';
export const UPDATE_AUTOPILOT_CONFIGS_FAILURE = 'UPDATE_AUTOPILOT_CONFIGS_FAILURE';

export const DELETE_AUTOPILOT_REQUEST = 'DELETE_AUTOPILOT_REQUEST';
export const DELETE_AUTOPILOT_SUCCESS = 'DELETE_AUTOPILOT_SUCCESS';
export const DELETE_AUTOPILOT_FAILURE = 'DELETE_AUTOPILOT_FAILURE';

export const UPDATE_AUTOPILOT_STATUS_REQUEST = 'UPDATE_AUTOPILOT_STATUS_REQUEST';
export const UPDATE_AUTOPILOT_STATUS_SUCCESS = 'UPDATE_AUTOPILOT_STATUS_SUCCESS';
export const UPDATE_AUTOPILOT_STATUS_FAILURE = 'UPDATE_AUTOPILOT_STATUS_FAILURE';


// Appointments Picker
export const FETCH_APPOINTMENT_REQUEST = 'FETCH_APPOINTMENT_REQUEST';
export const FETCH_APPOINTMENT_SUCCESS = 'FETCH_APPOINTMENT_SUCCESS';
export const FETCH_APPOINTMENT_FAILURE = 'FETCH_APPOINTMENT_FAILURE';

export const SELECT_APPOINTMENT_TIME_REQUEST = 'SELECT_APPOINTMENT_TIME_REQUEST';
export const SELECT_APPOINTMENT_TIME_SUCCESS = 'SELECT_APPOINTMENT_TIME_SUCCESS';
export const SELECT_APPOINTMENT_TIME_FAILURE = 'SELECT_APPOINTMENT_TIME_FAILURE';

// Appointments
export const FETCH_APPOINTMENTS_REQUEST = 'FETCH_APPOINTMENTS_REQUEST';
export const FETCH_APPOINTMENTS_SUCCESS = 'FETCH_APPOINTMENTS_SUCCESS';
export const FETCH_APPOINTMENTS_FAILURE = 'FETCH_APPOINTMENTS_FAILURE';

export const SET_APPOINTMENT_STATUS_REQUEST = 'SET_APPOINTMENT_STATUS_REQUEST';
export const SET_APPOINTMENT_STATUS_SUCCESS = 'SET_APPOINTMENT_STATUS_SUCCESS';
export const SET_APPOINTMENT_STATUS_FAILURE = 'SET_APPOINTMENT_STATUS_FAILURE';


// AAT = AppointmentAllocationTime
export const FETCH_AAT_REQUEST = 'FETCH_AAT_REQUEST';
export const FETCH_AAT_SUCCESS = 'FETCH_AAT_SUCCESS';
export const FETCH_AAT_FAILURE = 'FETCH_AAT_FAILURE';

export const SAVE_AAT_REQUEST = 'SAVE_AAT_REQUEST';
export const SAVE_AAT_SUCCESS = 'SAVE_AAT_SUCCESS';
export const SAVE_AAT_FAILURE = 'SAVE_AAT_FAILURE';

export const CREATE_AAT_REQUEST = 'CREATE_AAT_REQUEST';
export const CREATE_AAT_SUCCESS = 'CREATE_AAT_SUCCESS';
export const CREATE_AAT_FAILURE = 'CREATE_AAT_FAILURE';

export const DELETE_AAT_REQUEST = 'DELETE_AAT_REQUEST';
export const DELETE_AAT_SUCCESS = 'DELETE_AAT_SUCCESS';
export const DELETE_AAT_FAILURE = 'DELETE_AAT_FAILURE';

export const SWITCH_ACTIVE_AAT = 'SWITCH_ACTIVE_AAT';

// Development
export const FETCH_DEV_REQUEST = 'FETCH_DEV_REQUEST';
export const FETCH_DEV_SUCCESS = 'FETCH_DEV_SUCCESS';
export const FETCH_DEV_FAILURE = 'FETCH_DEV_FAILURE';

export const SAVE_WEBHOOK_REQUEST = 'SAVE_WEBHOOK_REQUEST';
export const SAVE_WEBHOOK_SUCCESS = 'SAVE_WEBHOOK_SUCCESS';
export const SAVE_WEBHOOK_FAILURE = 'SAVE_WEBHOOK_FAILURE';

export const CREATE_WEBHOOK_REQUEST = 'CREATE_WEBHOOK_REQUEST';
export const CREATE_WEBHOOK_SUCCESS = 'CREATE_WEBHOOK_SUCCESS';
export const CREATE_WEBHOOK_FAILURE = 'CREATE_WEBHOOK_FAILURE';

export const DELETE_WEBHOOK_REQUEST = 'DELETE_WEBHOOK_REQUEST';
export const DELETE_WEBHOOK_SUCCESS = 'DELETE_WEBHOOK_SUCCESS';
export const DELETE_WEBHOOK_FAILURE = 'DELETE_WEBHOOK_FAILURE';


//Campaign
export const FETCH_CAMPAIGNS_REQUEST = 'FETCH_CAMPAIGNS_REQUEST';
export const FETCH_CAMPAIGNS_SUCCESS = 'FETCH_CAMPAIGNS_SUCCESS';
export const FETCH_CAMPAIGNS_FAILURE = 'FETCH_CAMPAIGNS_FAILURE';

export const FETCH_CAMPAIGN_REQUEST = 'FETCH_CAMPAIGN_REQUEST';
export const FETCH_CAMPAIGN_SUCCESS = 'FETCH_CAMPAIGN_SUCCESS';
export const FETCH_CAMPAIGN_FAILURE = 'FETCH_CAMPAIGN_FAILURE';

export const SAVE_CAMPAIGN_REQUEST = 'SAVE_CAMPAIGN_REQUEST';
export const SAVE_CAMPAIGN_SUCCESS = 'SAVE_CAMPAIGN_SUCCESS';
export const SAVE_CAMPAIGN_FAILURE = 'SAVE_CAMPAIGN_FAILURE';

export const UPDATE_CAMPAIGN_REQUEST = 'UPDATE_CAMPAIGN_REQUEST';
export const UPDATE_CAMPAIGN_SUCCESS = 'UPDATE_CAMPAIGN_SUCCESS';
export const UPDATE_CAMPAIGN_FAILURE = 'UPDATE_CAMPAIGN_FAILURE';

export const DELETE_CAMPAIGN_REQUEST = 'DELETE_CAMPAIGN_REQUEST';
export const DELETE_CAMPAIGN_SUCCESS = 'DELETE_CAMPAIGN_SUCCESS';
export const DELETE_CAMPAIGN_FAILURE = 'DELETE_CAMPAIGN_FAILURE';

export const FETCH_CAMPAIGN_CANDIDATES_DATA_REQUEST = 'FETCH_CAMPAIGN_CANDIDATES_DATA_REQUEST';
export const FETCH_CAMPAIGN_CANDIDATES_DATA_SUCCESS = 'FETCH_CAMPAIGN_CANDIDATES_DATA_SUCCESS';
export const FETCH_CAMPAIGN_CANDIDATES_DATA_FAILURE = 'FETCH_CAMPAIGN_CANDIDATES_DATA_FAILURE';

export const LAUNCH_CAMPAIGN_REQUEST = 'LAUNCH_CAMPAIGN_REQUEST';
export const LAUNCH_CAMPAIGN_SUCCESS = 'LAUNCH_CAMPAIGN_SUCCESS';
export const LAUNCH_CAMPAIGN_FAILURE = 'LAUNCH_CAMPAIGN_FAILURE';

// Candidate availability 
export const FETCH_AVAILABILITY_REQUEST = 'FETCH_AVAILABILITY_REQUEST';
export const FETCH_AVAILABILITY_SUCCESS = 'FETCH_AVAILABILITY_SUCCESS';
export const FETCH_AVAILABILITY_FAILURE = 'FETCH_AVAILABILITY_FAILURE';

//PAYMENT
export const GENERATE_CHECKOUT_SESSION_REQUEST = 'GENERATE_CHECKOUT_SESSION_REQUEST';
export const GENERATE_CHECKOUT_SESSION_SUCCESS = 'GENERATE_CHECKOUT_SESSION_SUCCESS';
export const GENERATE_CHECKOUT_SESSION_FAILURE = 'GENERATE_CHECKOUT_SESSION_FAILURE';