export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';


export const FETCH_ASSISTANTS_REQUEST = 'FETCH_ASSISTANTS_REQUEST';
export const FETCH_ASSISTANTS_SUCCESS = 'FETCH_ASSISTANTS_SUCCESS';
export const FETCH_ASSISTANTS_FAILURE = 'FETCH_ASSISTANTS_FAILURE';

    export const CHANGE_ASSISTANT_STATUS_REQUEST = 'CHANGE_ASSISTANT_STATUS_REQUEST';
    export const CHANGE_ASSISTANT_STATUS_SUCCESS = 'CHANGE_ASSISTANT_STATUS_SUCCESS';
    export const CHANGE_ASSISTANT_STATUS_FAILURE = 'CHANGE_ASSISTANT_STATUS_FAILURE';


    export const ADD_ASSISTANT_REQUEST = 'ADD_ASSISTANTS_REQUEST';
    export const ADD_ASSISTANT_SUCCESS = 'ADD_ASSISTANT_SUCCESS';
    export const ADD_ASSISTANT_FAILURE = 'ADD_ASSISTANT_FAILURE';

    export const UPDATE_ASSISTANT_SETTINGS_REQUEST = 'UPDATE_ASSISTANT_SETTINGS_REQUEST';
    export const UPDATE_ASSISTANT_SETTINGS_SUCCESS = 'UPDATE_ASSISTANT_SETTINGS_SUCCESS';
    export const UPDATE_ASSISTANT_SETTINGS_FAILURE = 'UPDATE_ASSISTANT_SETTINGS_FAILURE';


export const FETCH_FLOW_REQUEST = 'FETCH_FLOW_REQUEST';
export const FETCH_FLOW_SUCCESS = 'FETCH_FLOW_SUCCESS';
export const FETCH_FLOW_FAILURE = 'FETCH_FLOW_FAILURE';
    // Groups
    export const ADD_GROUP_REQUEST = 'ADD_GROUP_REQUEST';
    export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
    export const ADD_GROUP_FAILURE = 'ADD_GROUP_FAILURE';

    export const EDIT_GROUP_REQUEST = 'EDIT_GROUP_REQUEST';
    export const EDIT_GROUP_SUCCESS = 'EDIT_GROUP_SUCCESS';
    export const EDIT_GROUP_FAILURE = 'EDIT_GROUP_FAILURE';

    export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST';
    export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
    export const DELETE_GROUP_FAILURE = 'DELETE_GROUP_FAILURE';

    // Block
    export const ADD_BLOCK_REQUEST = 'ADD_BLOCK_REQUEST';
    export const ADD_BLOCK_SUCCESS = 'ADD_BLOCK_SUCCESS';
    export const ADD_BLOCK_FAILURE = 'ADD_BLOCK_FAILURE';

    export const EDIT_BLOCK_REQUEST = 'EDIT_BLOCK_REQUEST';
    export const EDIT_BLOCK_SUCCESS = 'EDIT_BLOCK_SUCCESS';
    export const EDIT_BLOCK_FAILURE = 'EDIT_BLOCK_FAILURE';

    export const DELETE_BLOCK_REQUEST = 'DELETE_BLOCK_REQUEST';
    export const DELETE_BLOCK_SUCCESS = 'DELETE_BLOCK_FAILURE';
    export const DELETE_BLOCK_FAILURE = 'DELETE_BLOCK_FAILURE';



// Profile
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

    export const SAVE_PROFILE_DETAILS_REQUEST = 'SAVE_PROFILE_DETAILS_REQUEST';
    export const SAVE_PROFILE_DETAILS_SUCCESS = 'SAVE_PROFILE_DETAILS_SUCCESS';
    export const SAVE_PROFILE_DETAILS_FAILURE = 'SAVE_PROFILE_DETAILS_FAILURE';

    export const SAVE_DATA_SETTINGS_REQUEST = 'SAVE_DATA_SETTINGS_REQUEST';
    export const SAVE_DATA_SETTINGS_SUCCESS = 'SAVE_DATA_SETTINGS_SUCCESS';
    export const SAVE_DATA_SETTINGS_FAILURE = 'SAVE_DATA_SETTINGS_FAILURE';

// User Input
export const FETCH_USERINPUT_REQUEST = 'FETCH_USERINPUT_REQUEST';
export const FETCH_USERINPUT_SUCCESS = 'FETCH_USERINPUT_SUCCESS';
export const FETCH_USERINPUT_FAILURE = 'FETCH_USERINPUT_FAILURE';

    export const CLEAR_ALL_USERINPUT_REQUEST = 'CLEAR_ALL_USERINPUT_REQUEST';
    export const CLEAR_ALL_USERINPUT_SUCCESS = 'CLEAR_ALL_USERINPUT_SUCCESS';
    export const CLEAR_ALL_USERINPUT_FAILURE = 'CLEAR_ALL_USERINPUT_FAILURE';

// Solutions
export const GET_SOLUTIONS_REQUEST = 'GET_SOLUTIONS_REQUEST';
export const GET_SOLUTIONS_SUCCESS = 'GET_SOLUTIONS_SUCCESS';
export const GET_SOLUTIONS_FAILURE = 'GET_SOLUTIONS_FAILURE';

    export const ADD_SOLUTION_REQUEST = 'ADD_SOLUTION_REQUEST';
    export const ADD_SOLUTION_SUCCESS = 'ADD_SOLUTION_SUCCESS';
    export const ADD_SOLUTION_FAILURE = 'ADD_SOLUTION_FAILURE';
