export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';


export const FETCH_ASSISTANTS_REQUEST = 'FETCH_ASSISTANTS_REQUEST';
export const FETCH_ASSISTANTS_SUCCESS = 'FETCH_ASSISTANTS_SUCCESS';
export const FETCH_ASSISTANTS_FAILURE = 'FETCH_ASSISTANTS_FAILURE';

    export const ADD_ASSISTANT_REQUEST = 'ADD_ASSISTANTS_REQUEST';
    export const ADD_ASSISTANT_SUCCESS = 'ADD_ASSISTANT_SUCCESS';
    export const ADD_ASSISTANT_FAILURE = 'ADD_ASSISTANT_FAILURE';

    export const UPDATE_ASSISTANT_SETTINGS_REQUEST = 'UPDATE_ASSISTANT_SETTINGS_REQUEST';
    export const UPDATE_ASSISTANT_SETTINGS_SUCCESS = 'UPDATE_ASSISTANT_SETTINGS_SUCCESS';
    export const UPDATE_ASSISTANT_SETTINGS_FAILURE = 'UPDATE_ASSISTANT_SETTINGS_FAILURE';


export const FETCH_FLOW_REQUEST = 'FETCH_FLOW_REQUEST';
export const FETCH_FLOW_SUCCESS = 'FETCH_FLOW_SUCCESS';
export const FETCH_FLOW_FAILURE = 'FETCH_FLOW_FAILURE';

    export const ADD_GROUP_REQUEST = 'ADD_GROUP_REQUEST';
    export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
    export const ADD_GROUP_FAILURE = 'ADD_GROUP_FAILURE';

    export const EDIT_GROUP_REQUEST = 'EDIT_GROUP_REQUEST';
    export const EDIT_GROUP_SUCCESS = 'EDIT_GROUP_SUCCESS';
    export const EDIT_GROUP_FAILURE = 'EDIT_GROUP_FAILURE';

    export const DELETE_GROUP_REQUEST = 'DELETE_GROUP_REQUEST';
    export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
    export const DELETE_GROUP_FAILURE = 'DELETE_GROUP_FAILURE';




