export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';


export const FETCH_ASSISTANTS_REQUEST = 'FETCH_ASSISTANTS_REQUEST';
export const FETCH_ASSISTANTS_SUCCESS = 'FETCH_ASSISTANTS_SUCCESS';
export const FETCH_ASSISTANTS_FAILURE = 'FETCH_ASSISTANTS_FAILURE';


export const FETCH_FLOW_REQUEST = 'FETCH_FLOW_REQUEST';
export const FETCH_FLOW_SUCCESS = 'FETCH_FLOW_SUCCESS';
export const FETCH_FLOW_FAILURE = 'FETCH_FLOW_FAILURE';


