export const dummyExcelData = {
    "headers": ["Title", "First Name", "Last Name", " Email", "Employment Type", "Employment Type Looking for", "Job Types", "Gender", "linkedln", "Current Salary", "Desired Salary", "Company", "Contract Rate", "Education", "Degree", "Employer (Company)", "Mobile", "Job Title 1", "Keyword", "Skills", "Start1. MM-DD-YYYY", "End1. MM-DD-YYYY", "Zip code"],
    "data": [{
        "Title": "Mr",
        "First Name": "MehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdi",
        "Last Name": "Este",
        " Email": "m.este@thesearchbase.com",
        "Employment Type": "FULL-TIME",
        "Employment Type Looking for": "PERMANENT",
        "Job Types": "PERMANENT",
        "Gender": "MALE",
        "linkedln": "https://www.linkedin.com/in/mehdi-este-142460107/",
        "Current Salary": 100000,
        "Desired Salary": 250000,
        "Company": "entrepreneurship, sales, engineering",
        "Contract Rate": 0,
        "Education": "Degree",
        "Degree": "University",
        "Employer (Company)": "TheSearchBase",
        "Mobile": 7777777777,
        "Job Title 1": "CEO & Director",
        "Keyword": "sales director, well connected",
        "Skills": "Python, React, Flask",
        "Start1. MM-DD-YYYY": "2026-09-23T21:00:00.000Z",
        "End1. MM-DD-YYYY": "2019-03-02T21:00:00.000Z",
        "Zip code": "W1 3AE"
    }, {
        "Title": "Mrs",
        "First Name": "Alexa",
        "Last Name": "Amazon",
        " Email": "amazon@amazon.co.uk",
        "Employment Type": "FULL-TIME",
        "Employment Type Looking for": "CONTRACT",
        "Job Types": "CONTRACT",
        "Gender": "FEMALE",
        "Current Salary": 350,
        "Desired Salary": 500,
        "Company": "customer service, sales",
        "Contract Interval(Days until end so 60 is like 2 month contract)": 60,
        "Contract Rate": 500,
        "Education": "Masters",
        "Degree": "University",
        "Employer (Company)": "Amazon",
        "Mobile": 34583945,
        "Job Title 1": "Sales Assistant",
        "Keyword": "sales support, sales adminstrator",
        "Skills": "MySQL",
        "Start1. MM-DD-YYYY": "Just Looking",
        "End1. MM-DD-YYYY": "2019-03-03T21:00:00.000Z",
        "Zip code": "W4 6YT"
    }, {
        "Title": "Mr",
        "First Name": "Evgeniy",
        "Last Name": "Tonchev",
        " Email": "tonchev@thesearchbase.com",
        "Employment Type": "PART-TIME",
        "Employment Type Looking for": "PERMANENT",
        "Job Types": "PERMANENT",
        "Gender": "MALE",
        "linkedln": "https://www.linkedin.com/in/mehdi-este-142460107/",
        "Current Salary": 100000,
        "Desired Salary": 150000,
        "Company": "Technology, Engineering",
        "Contract Rate": 0,
        "Education": "Degree",
        "Degree": "GCSE",
        "Employer (Company)": "TheSearchBase",
        "Mobile": 456000,
        "Job Title 1": "CTO & Director",
        "Keyword": "cto, head of engineering",
        "Skills": "Python, MySQL, Linux",
        "Start1. MM-DD-YYYY": "2026-09-22T21:00:00.000Z",
        "End1. MM-DD-YYYY": "2019-03-04T21:00:00.000Z",
        "Zip code": "S5 6ND"
    }, {
        "Title": "Mr",
        "First Name": "Mehdi",
        "Last Name": "Este",
        " Email": "m.este@thesearchbase.com",
        "Employment Type": "PART-TIME",
        "Employment Type Looking for": "PERMANENT",
        "Job Types": "CONTRACT",
        "Gender": "MALE",
        "Current Salary": 400000,
        "Desired Salary": 50000,
        "Company": "entrepreneurship, sales, engineering",
        "Contract Interval(Days until end so 60 is like 2 month contract)": 120,
        "Contract Rate": 250,
        "Education": "PhD",
        "Degree": "A-Levels",
        "Employer (Company)": "Google",
        "Mobile": 6546456456,
        "Job Title 1": "Software Enginner",
        "Keyword": ".net developer, machine learning",
        "Skills": "python, C#, java",
        "Start1. MM-DD-YYYY": "Just Looking",
        "End1. MM-DD-YYYY": "2019-03-05T21:00:00.000Z",
        "Zip code": "W1 3AE"
    }, {
        "Title": "Mrs",
        "First Name": "Alexa",
        "Last Name": "Amazon",
        " Email": "amazon@amazon.co.uk",
        "Employment Type": "FULL-TIME",
        "Employment Type Looking for": "PERMANENT",
        "Job Types": "CONTRACT",
        "Gender": "FEMALE",
        "Current Salary": 200,
        "Desired Salary": 40000,
        "Company": "customer service, sales",
        "Contract Interval(Days until end so 60 is like 2 month contract)": 90,
        "Contract Rate": 150,
        "Education": "Degree",
        "Degree": "University",
        "Employer (Company)": "Amazon",
        "Mobile": 456456456,
        "Job Title 1": "Sales Director",
        "Keyword": "sales strategy, sales qualification, sales leads",
        "Skills": "Salesforce CRM, list of contacts",
        "Start1. MM-DD-YYYY": "Just Looking",
        "End1. MM-DD-YYYY": "2019-03-06T21:00:00.000Z",
        "Zip code": "W4 6YT"
    }, {
        "Title": "Mr",
        "First Name": "Evgeniy",
        "Last Name": "Tonchev",
        " Email": "tonchev@thesearchbase.com",
        "Employment Type": "FULL-TIME",
        "Employment Type Looking for": "CONTRACT",
        "Job Types": "CONTRACT",
        "Gender": "MALE",
        "Current Salary": 300000,
        "Desired Salary": 450,
        "Company": "Technology, Engineering",
        "Contract Interval(Days until end so 60 is like 2 month contract)": 30,
        "Contract Rate": 100,
        "Education": "Masters",
        "Degree": "University",
        "Employer (Company)": "TheSearchBase",
        "Mobile": 45645645645,
        "Job Title 1": "Server Side Developer",
        "Keyword": "React developer, python developer",
        "Skills": "Python, React, Redux, Saga",
        "Start1. MM-DD-YYYY": "2021-10-30T21:00:00.000Z",
        "End1. MM-DD-YYYY": "2019-03-07T21:00:00.000Z",
        "Zip code": "S5 6ND"
    }]
};

export const validData = [{
    "Name": {
        "data": "Alexa Amazon",
        "message": null,
        "isValid": true,
        "originalColumns": ["First Name", "Last Name"]
    },
    "Email": {"data": "amazon@amazon.co.uk", "message": null, "isValid": true, "originalColumns": [" Email"]},
    "Telephone": {"data": "34583945", "message": null, "isValid": true, "originalColumns": ["Mobile"]},
    "LinkdinURL": {"data": "", "message": null, "isValid": true, "originalColumns": ["linkedln"]},
    "PostCode": {"data": "W4 6YT", "message": null, "isValid": true, "originalColumns": ["Zip code"]},
    "Gender": {"data": "FEMALE", "message": null, "isValid": true, "originalColumns": ["Gender"]},
    "Degree": {"data": "University", "message": null, "isValid": true, "originalColumns": ["Degree"]}
}, {
    "Name": {
        "data": "Evgeniy Tonchev",
        "message": null,
        "isValid": true,
        "originalColumns": ["First Name", "Last Name"]
    },
    "Email": {"data": "tonchev@thesearchbase.com", "message": null, "isValid": true, "originalColumns": [" Email"]},
    "Telephone": {"data": "456000", "message": null, "isValid": true, "originalColumns": ["Mobile"]},
    "LinkdinURL": {
        "data": "https://www.linkedin.com/in/mehdi-este-142460107/",
        "message": null,
        "isValid": true,
        "originalColumns": ["linkedln"]
    },
    "PostCode": {"data": "S5 6ND", "message": null, "isValid": true, "originalColumns": ["Zip code"]},
    "Gender": {"data": "MALE", "message": null, "isValid": true, "originalColumns": ["Gender"]},
    "Degree": {"data": "GCSE", "message": null, "isValid": true, "originalColumns": ["Degree"]}
}, {
    "Name": {"data": "Mehdi Este", "message": null, "isValid": true, "originalColumns": ["First Name", "Last Name"]},
    "Email": {"data": "m.este@thesearchbase.com", "message": null, "isValid": true, "originalColumns": [" Email"]},
    "Telephone": {"data": "6546456456", "message": null, "isValid": true, "originalColumns": ["Mobile"]},
    "LinkdinURL": {"data": "", "message": null, "isValid": true, "originalColumns": ["linkedln"]},
    "PostCode": {"data": "W1 3AE", "message": null, "isValid": true, "originalColumns": ["Zip code"]},
    "Gender": {"data": "MALE", "message": null, "isValid": true, "originalColumns": ["Gender"]},
    "Degree": {"data": "A-Levels", "message": null, "isValid": true, "originalColumns": ["Degree"]}
}, {
    "Name": {"data": "Alexa Amazon", "message": null, "isValid": true, "originalColumns": ["First Name", "Last Name"]},
    "Email": {"data": "amazon@amazon.co.uk", "message": null, "isValid": true, "originalColumns": [" Email"]},
    "Telephone": {"data": "456456456", "message": null, "isValid": true, "originalColumns": ["Mobile"]},
    "LinkdinURL": {"data": "", "message": null, "isValid": true, "originalColumns": ["linkedln"]},
    "PostCode": {"data": "W4 6YT", "message": null, "isValid": true, "originalColumns": ["Zip code"]},
    "Gender": {"data": "FEMALE", "message": null, "isValid": true, "originalColumns": ["Gender"]},
    "Degree": {"data": "University", "message": null, "isValid": true, "originalColumns": ["Degree"]}
}, {
    "Name": {
        "data": "Evgeniy Tonchev",
        "message": null,
        "isValid": true,
        "originalColumns": ["First Name", "Last Name"]
    },
    "Email": {"data": "tonchev@thesearchbase.com", "message": null, "isValid": true, "originalColumns": [" Email"]},
    "Telephone": {"data": "45645645645", "message": null, "isValid": true, "originalColumns": ["Mobile"]},
    "LinkdinURL": {"data": "", "message": null, "isValid": true, "originalColumns": ["linkedln"]},
    "PostCode": {"data": "S5 6ND", "message": null, "isValid": true, "originalColumns": ["Zip code"]},
    "Gender": {"data": "MALE", "message": null, "isValid": true, "originalColumns": ["Gender"]},
    "Degree": {"data": "University", "message": null, "isValid": true, "originalColumns": ["Degree"]}
}];

export const invalidData = [{
    "Name": {
        "data": "MehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdi Este",
        "message": "MehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdiMehdi Este is exceeding the string length 64",
        "isValid": false,
        "originalColumns": ["First Name", "Last Name"]
    },
    "Email": {"data": "m.este@thesearchbase.com", "message": null, "isValid": true, "originalColumns": [" Email"]},
    "Telephone": {"data": "7777777777", "message": null, "isValid": true, "originalColumns": ["Mobile"]},
    "LinkdinURL": {
        "data": "https://www.linkedin.com/in/mehdi-este-142460107/",
        "message": null,
        "isValid": true,
        "originalColumns": ["linkedln"]
    },
    "PostCode": {"data": "W1 3AE", "message": null, "isValid": true, "originalColumns": ["Zip code"]},
    "Gender": {"data": "MALE", "message": null, "isValid": true, "originalColumns": ["Gender"]},
    "Degree": {"data": "University", "message": null, "isValid": true, "originalColumns": ["Degree"]}
}];


export const jobsExcelSheet = {
    "headers": ["Employee Name", "Employee Number", "State", "Zip", "DOB", "Age", "Sex", "MaritalDesc", "CitizenDesc", "Hispanic/Latino", "RaceDesc", "Date of Hire", "Reason For Term", "Employment Status", "Department", "Position", "Pay Rate", "Manager Name", "Employee Source", "Performance Score"],
    "data": [
        {
            "Employee Name": "Brown, Mia",
            "Employee Number": 1103024456,
            "State": "MA",
            "Zip": 1450,
            "DOB": "1985-11-23T21:00:00.000Z",
            "Age": 32,
            "Sex": "Female",
            "MaritalDesc": "Married",
            "CitizenDesc": "US Citizen",
            "Hispanic/Latino": "No",
            "RaceDesc": "Black or African American",
            "Date of Hire": "2008-10-26T21:00:00.000Z",
            "Reason For Term": "N/A - still employed",
            "Employment Status": "Active",
            "Department": "Admin Offices",
            "Position": "Accountant I",
            "Pay Rate": 28.5,
            "Manager Name": "Brandon R. LeBlanc",
            "Employee Source": "Diversity Job Fair",
            "Performance Score": "Fully Meets"
        }, {
            "Employee Name": "LaRotonda, William  ",
            "Employee Number": 1106026572,
            "State": "MA",
            "Zip": 1460,
            "DOB": "1984-04-25T21:00:00.000Z",
            "Age": 33,
            "Sex": "Male",
            "MaritalDesc": "Divorced",
            "CitizenDesc": "US Citizen",
            "Hispanic/Latino": "No",
            "RaceDesc": "Black or African American",
            "Date of Hire": "2014-01-05T21:00:00.000Z",
            "Reason For Term": "N/A - still employed",
            "Employment Status": "Active",
            "Department": "Admin Offices",
            "Position": "Accountant I",
            "Pay Rate": 23,
            "Manager Name": "Brandon R. LeBlanc",
            "Employee Source": "Website Banner Ads",
            "Performance Score": "Fully Meets"
        }, {
            "Employee Name": "Steans, Tyrone  ",
            "Employee Number": 1302053333,
            "State": "MA",
            "Zip": 2703,
            "DOB": "1986-08-31T21:00:00.000Z",
            "Age": 31,
            "Sex": "Male",
            "MaritalDesc": "Single",
            "CitizenDesc": "US Citizen",
            "Hispanic/Latino": "No",
            "RaceDesc": "White",
            "Date of Hire": "2014-09-28T21:00:00.000Z",
            "Reason For Term": "N/A - still employed",
            "Employment Status": "Active",
            "Department": "Admin Offices",
            "Position": "Accountant I",
            "Pay Rate": 29,
            "Manager Name": "Brandon R. LeBlanc",
            "Employee Source": "Internet Search",
            "Performance Score": "Fully Meets"
        }, {
            "Employee Name": "Howard, Estelle",
            "Employee Number": 1211050782,
            "State": "MA",
            "Zip": 2170,
            "DOB": "1985-09-15T21:00:00.000Z",
            "Age": 32,
            "Sex": "Female",
            "MaritalDesc": "Married",
            "CitizenDesc": "US Citizen",
            "Hispanic/Latino": "No",
            "RaceDesc": "White",
            "Date of Hire": "2015-02-15T21:00:00.000Z",
            "Date of Termination": "2015-04-14T21:00:00.000Z",
            "Reason For Term": "N/A - still employed",
            "Employment Status": "Active",
            "Department": "Admin Offices",
            "Position": "Administrative Assistant",
            "Pay Rate": 21.5,
            "Manager Name": "Brandon R. LeBlanc",
            "Employee Source": "Pay Per Click - Google",
            "Performance Score": "N/A- too early to review"
        }, {
            "Employee Name": "Singh, Nan ",
            "Employee Number": 1307059817,
            "State": "MA",
            "Zip": 2330,
            "DOB": "1988-05-18T21:00:00.000Z",
            "Age": 29,
            "Sex": "Female",
            "MaritalDesc": "Single",
            "CitizenDesc": "US Citizen",
            "Hispanic/Latino": "No",
            "RaceDesc": "White",
            "Date of Hire": "2015-04-30T21:00:00.000Z",
            "Reason For Term": "N/A - still employed",
            "Employment Status": "Active",
            "Department": "Admin Offices",
            "Position": "Administrative Assistant",
            "Pay Rate": 16.56,
            "Manager Name": "Brandon R. LeBlanc",
            "Employee Source": "Website Banner Ads",
            "Performance Score": "N/A- too early to review"
        }]
};

